name: MSBuild
on:
  push:
    branches:
      - main
      - actions
  #pull_request:
  #  branches: [ main ]
  workflow_dispatch:

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: ./Code/Flowframes.sln

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

  PYTHON_MINOR: 8
  PYTHON_PATCH: 19
  PYTHON_PATCH_PATH: 10

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Cache Commit SHA
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $env:GITHUB_OUTPUT
    #- name: Check Commit SHA
    #  run: echo ${{steps.vars.outputs.sha_short}}

    - name: Add Python to PATH
      uses: actions/setup-python@v5
      with:
        python-version: 3.${{env.PYTHON_MINOR}}.${{env.PYTHON_PATCH_PATH}}

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Add NuGet to PATH
      uses: nuget/setup-nuget@v2

    - name: Embed Python
      working-directory: .\pkgs
      run: |
        Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope Process
        Invoke-WebRequest -Uri "https://raw.githubusercontent.com/jtmoon79/PythonEmbed4Win/main/PythonEmbed4Win.ps1" -OutFile "PythonEmbed4Win.ps1"
        (Get-Content .\PythonEmbed4Win.ps1) -replace 'www\.python.org\/ftp\/python', 'raw.githubusercontent.com/adang1345/PythonWindows/blob/master' | Set-Content .\PythonEmbed4Win.ps1
        (Get-Content .\PythonEmbed4Win.ps1) -replace '3\.8\.10', '3.8.19' | Set-Content .\PythonEmbed4Win.ps1
        .\PythonEmbed4Win.ps1 -Version 3.${{env.PYTHON_MINOR}}.${{env.PYTHON_PATCH}} -Path py-amp -Arch amd64

    - name: Embed PyTorch
      run: |
        cd .\pkgs\py-amp
        .\python.exe -m pip install numpy==1.19.3
        .\python.exe -m pip install torch==1.8.2 torchvision==0.9.2 --extra-index-url https://download.pytorch.org/whl/lts/1.8/cu111
        .\python.exe -m pip install opencv-python sk-video imageio

    - name: NuGet Restore
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build Flowframes
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform="x64" ${{env.SOLUTION_FILE_PATH}}

    - name: Build Package
      working-directory: .\Build
      run: cmd /C CALL PackageBuild.bat ${{steps.vars.outputs.sha_short}} N Y N

    - name: Upload Package
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: error
        name: Flowframes
        path: ./**/FF-${{steps.vars.outputs.sha_short}}-Full-RTX3000.7z
