name: MSBuild
on:
  push:
    branches:
      - main
      - actions
  #pull_request:
  #  branches: [ main ]
  workflow_dispatch:

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: ./Code/Flowframes.sln

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

  CUDA_VERSION: 111
  PYTHON_MINOR: 8
  PYTHON_PATCH: 19
  PYTHON_PATCH_SETUP: 10

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Cache Commit SHA
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $env:GITHUB_OUTPUT
    #- name: Check Commit SHA
    #  run: echo ${{steps.vars.outputs.sha_short}}

    - name: Add Python to PATH
      uses: actions/setup-python@v5
      with:
        python-version: 3.${{env.PYTHON_MINOR}}.${{env.PYTHON_PATCH_SETUP}}

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Add NuGet to PATH
      uses: nuget/setup-nuget@v2

    - name: NuGet Restore
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build Python
      shell: bash
      run: |
        cd ./pkgs
        curl https://raw.githubusercontent.com/adang1345/PythonWindows/blob/master/3.${{env.PYTHON_MINOR}}.${{env.PYTHON_PATCH}}/python-3.${{env.PYTHON_MINOR}}.${{env.PYTHON_PATCH}}-embed-amd64.zip -o py-embed.zip
        unzip py-embed.zip -d py-amp
        cd py-amp
        echo 'import site' >> ./python3${{env.PYTHON_MINOR}}._pth
        curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
        ./python.exe get-pip.py
        ./python -m pip install numpy==1.19.3
        ./python -m pip install torch==1.8.1+cu{{env.CUDA_VERSION}} torchvision==0.9.1+cu{{env.CUDA_VERSION}} -f https://download.pytorch.org/whl/torch_stable.html
        ./python.exe -m pip install opencv-python sk-video imageio
        ls

    - name: Build Flowframes
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform="x64" ${{env.SOLUTION_FILE_PATH}}

    - name: Build Package
      working-directory: .\Build
      run: cmd /C CALL PackageBuild.bat ${{steps.vars.outputs.sha_short}} N Y N

    - name: Upload Package
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: error
        name: Flowframes
        path: ./**/FF-${{steps.vars.outputs.sha_short}}-Full-RTX3000.7z
